## Numpy

In [2]:
conda install numpy

Solving environment: done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [1]:
#Initially lets import numpy

import numpy as np

In [2]:
my_lst = [1,2,3,4,5]

arr=np.array(my_lst)

In [3]:
type(arr)

numpy.ndarray

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
arr.shape

(5,)

In [22]:
#Multinested array
my_lst1= [1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [9]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [10]:
arr.shape

(3, 5)

In [11]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [12]:
arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9]])

### Indexing

In [20]:
## Accessing the array elements

arr = np.array([1,2,3,4,5,6,7,8,9])

In [25]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [24]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [26]:
arr[1:,2:4]

array([[4, 5],
       [6, 8]])

In [27]:
arr[1,1:4]

array([3, 4, 5])

In [28]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [30]:
## copy() function and broadcasting

arr[3:]=100

In [31]:
arr

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [32]:
arr1 = arr

In [33]:
arr1[3:]=500
print(arr1)

[  0   1   2 500 500 500 500 500 500 500]


In [34]:
arr

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [36]:
### Some conditions very useful in Exploratory Data Analysis

val = 4
arr<2




array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [37]:
arr*2


array([   0,    2,    4, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [38]:
arr>2

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [39]:
arr[arr<2]

array([0, 1])

In [40]:
#Create arrays and reshape

np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [41]:
arr1= np.arange(0,10).reshape(2,5)

In [42]:
arr2= np.arange(0,10).reshape(2,5)

In [43]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [46]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [49]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [50]:
#Random Distribution
np.random.rand(3,3)

array([[0.1296235 , 0.74092739, 0.09760656],
       [0.40905387, 0.58381367, 0.34173575],
       [0.32503174, 0.00121978, 0.81056641]])

In [51]:
arr_ex=np.random.randn(4,4)

In [52]:
arr_ex

array([[-1.03314693, -2.08379838, -1.77675693,  0.8982412 ],
       [ 1.1911171 , -1.18183981,  2.01030531, -0.16126493],
       [ 0.92758874, -0.34283354, -0.68061101,  0.91152819],
       [-1.44590337,  1.87687295,  0.54927742,  0.30721716]])